import { CSSProperties } from "react";

interface CSSStyles {
  row?: CSSProperties;
  item?: CSSProperties;
  oneLeft?: CSSProperties;
  oneRight?: CSSProperties;
  oneTop?: CSSProperties;
  oneBottom?: CSSProperties;
  twoHorizontal?: CSSProperties;
  twoVertical?: CSSProperties;
  twoTopLeft?: CSSProperties;
  twoTopLeftInner?: CSSProperties;
  twoTopRight?: CSSProperties;
  twoTopRightInner?: CSSProperties;
  twoBottomLeft?: CSSProperties;
  twoBottomLeftInner?: CSSProperties;
  twoBottomRight?: CSSProperties;
  twoBottomRightInner?: CSSProperties;
  threeTop?: CSSProperties;
  threeTopInnerLeft?: CSSProperties;
  threeTopInnerRight?: CSSProperties;
  threeBottom?: CSSProperties;
  threeBottomInnerLeft?: CSSProperties;
  threeBottomInnerRight?: CSSProperties;
  threeLeft?: CSSProperties;
  threeLeftInnerTop?: CSSProperties;
  threeLeftInnerBottom?: CSSProperties;
  threeRight?: CSSProperties;
  threeRightInnerTop?: CSSProperties;
  threeRightInnerBottom?: CSSProperties;
  zero?: CSSProperties;
}

export const styles: CSSStyles = {
  row: {
    display: "flex",
    flexDirection: "row",
  },
  item: {
    height: 20,
    width: 20,
    backgroundColor: "black",
    display: "flex",
  },
  oneLeft: {
    height: 10,
    width: 18,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    borderRightWidth: 0,
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
    alignSelf: "center",
  },
  oneRight: {
    height: 10,
    width: 18,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    borderLeftWidth: 0,
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
    alignSelf: "center",
  },
  oneTop: {
    height: 18,
    width: 10,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    borderBottomWidth: 0,
    borderTopRightRadius: 5,
    borderTopLeftRadius: 5,
    alignSelf: "center",
    justifySelf: "center",
    transform: "translateX(3px)",
  },
  oneBottom: {
    height: 18,
    width: 10,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    borderTopWidth: 0,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    alignSelf: "center",
    justifySelf: "center",
    transform: "translateX(3px)",
  },
  twoHorizontal: {
    height: 10,
    width: 20,
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    alignSelf: "center",
  },
  twoVertical: {
    height: 20,
    width: 10,
    borderTopWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    transform: "translateX(3px)",
  },
  twoTopLeft: {
    height: 15,
    width: 15,
    borderTopWidth: 0,
    borderBottomWidth: 2,
    borderLeftWidth: 0,
    borderRightWidth: 2,
    borderBottomRightRadius: 5,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
  },
  twoTopLeftInner: {
    height: 3,
    width: 3,
    borderTopWidth: 0,
    borderBottomWidth: 2,
    borderLeftWidth: 0,
    borderRightWidth: 2,
    borderBottomRightRadius: 3,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
  },
  twoTopRight: {
    height: 15,
    width: 15,
    borderTopWidth: 0,
    borderBottomWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 0,
    borderBottomLeftRadius: 5,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    transform: "translateX(3px)",
  },
  twoTopRightInner: {
    height: 3,
    width: 3,
    borderTopWidth: 0,
    borderBottomWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 0,
    borderBottomLeftRadius: 3,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    transform: "translateX(10px)",
  },
  twoBottomLeft: {
    height: 15,
    width: 15,
    borderTopWidth: 2,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 2,
    borderTopRightRadius: 5,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    alignSelf: "flex-end",
    display: "flex",
  },
  twoBottomLeftInner: {
    height: 3,
    width: 3,
    borderTopWidth: 2,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 2,
    borderTopRightRadius: 3,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    alignSelf: "flex-end",
  },
  twoBottomRight: {
    height: 15,
    width: 15,
    borderTopWidth: 2,
    borderBottomWidth: 0,
    borderLeftWidth: 2,
    borderRightWidth: 0,
    borderTopLeftRadius: 5,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    alignSelf: "flex-end",
    justifyContent: "flex-end",
    transform: "translateX(3px)",
    display: "flex",
  },
  twoBottomRightInner: {
    height: 3,
    width: 3,
    borderTopWidth: 2,
    borderBottomWidth: 0,
    borderLeftWidth: 2,
    borderRightWidth: 0,
    borderTopLeftRadius: 3,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    alignSelf: "flex-end",
  },
  threeTop: {
    height: 15,
    width: 20,
    borderWidth: 0,
    borderBottomWidth: 2,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  threeTopInnerLeft: {
    height: 3,
    width: 3,
    borderTopWidth: 0,
    borderBottomWidth: 2,
    borderLeftWidth: 0,
    borderRightWidth: 2,
    borderBottomRightRadius: 3,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
  },
  threeTopInnerRight: {
    height: 3,
    width: 3,
    borderTopWidth: 0,
    borderBottomWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 0,
    borderBottomLeftRadius: 3,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
  },
  threeBottom: {
    height: 15,
    width: 20,
    borderWidth: 0,
    borderTopWidth: 2,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignSelf: "flex-end",
    alignItems: "flex-end",
  },
  threeBottomInnerLeft: {
    height: 3,
    width: 3,
    borderTopWidth: 2,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 2,
    borderTopRightRadius: 3,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
  },
  threeBottomInnerRight: {
    height: 3,
    width: 3,
    borderTopWidth: 2,
    borderBottomWidth: 0,
    borderLeftWidth: 2,
    borderRightWidth: 0,
    borderTopLeftRadius: 3,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
  },
  threeLeft: {
    height: 20,
    width: 15,
    borderWidth: 0,
    borderRightWidth: 2,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  threeLeftInnerTop: {
    height: 3,
    width: 3,
    borderTopWidth: 0,
    borderBottomWidth: 2,
    borderLeftWidth: 0,
    borderRightWidth: 2,
    borderBottomRightRadius: 3,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
  },
  threeLeftInnerBottom: {
    height: 3,
    width: 3,
    borderTopWidth: 2,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 2,
    borderTopRightRadius: 3,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
  },
  threeRight: {
    height: 20,
    width: 15,
    borderWidth: 0,
    borderLeftWidth: 2,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    transform: "translateX(3px)",
    alignItems: "flex-end",
  },
  threeRightInnerTop: {
    height: 3,
    width: 3,
    borderTopWidth: 0,
    borderBottomWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 0,
    borderBottomLeftRadius: 3,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
  },
  threeRightInnerBottom: {
    height: 3,
    width: 3,
    borderTopWidth: 2,
    borderBottomWidth: 0,
    borderLeftWidth: 2,
    borderRightWidth: 0,
    borderTopLeftRadius: 3,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
  },
  zero: {
    width: 16,
    height: 16,
    borderRadius: 16,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "rgb(28, 28, 191)",
  },
};
